### ISSUE TITLE
Missing file "resources/growth_scores_gene_sets.gmt"

### ISSUE THREAD

**Issue by robindar** [broadinstitute/wot#1]
Hi,

I think a file is missing here, either it was not added to the repo or it was moved and its
location was not updated.

The issue occurs when running
```bash
wot gene_set_scores --matrix <matrixfile>
```

In [wot/commands/gene_set_scores.py](https://github.com/broadinstitute/wot/blob/develop/wot/commands/gene_set_scores.py), on line 55,

the *gene_sets* variable defaults to **'wot/resources/growth_scores_gene_sets.gmt'**.

However, that file is not present, which triggers a **FileNotFoundError** at runtime.

Thanks !

**Comment by joshua-gould** [comment]
Added the file.
