### ISSUE TITLE
cannot find "wot" command

### ISSUE THREAD

**Issue by wulabupenn** [broadinstitute/wot#22]
I cannot find the "wot" in environment after "pip install --user wot" was done.

**Comment by wulabupenn** [comment]
relf-solved.

**Comment by rosshandler** [comment]
How was this solved? I am having the same issue

**Comment by rosshandler** [comment]
Okay, this solution worked for me (as pip install --user installs the packages on ~/.local/)

export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"

Cheers
