### ISSUE TITLE
wot trajectory crashing

### ISSUE THREAD

**Issue by ktpolanski** [broadinstitute/wot#23]
Hello. I've tried to run wot on my data, and am getting a rather confusing error when attempting to infer the trajectory:

	ubuntu@mapcloud1:/mnt/endometrium/N6.5-organoids-split$ wot trajectory --tmap tmaps --cell_set clusters.gmt --time 3 --out traj.txt
	/usr/local/lib/python3.6/dist-packages/numba/errors.py:104: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
	  warnings.warn(msg)
	Traceback (most recent call last):
	  File "/usr/local/bin/wot", line 11, in <module>
		sys.exit(main())
	  File "/usr/local/lib/python3.6/dist-packages/wot/__main__.py", line 23, in main
		cmd.main(command_args)
	  File "/usr/local/lib/python3.6/dist-packages/wot/commands/trajectory.py", line 23, in main
		trajectory_ds = tmap_model.compute_trajectories(populations)
	  File "/usr/local/lib/python3.6/dist-packages/wot/tmap/transport_map_model.py", line 97, in compute_trajectories
		var=pd.DataFrame(index=population_names))
	  File "/usr/local/lib/python3.6/dist-packages/anndata/base.py", line 671, in __init__
		filename=filename, filemode=filemode)
	  File "/usr/local/lib/python3.6/dist-packages/anndata/base.py", line 880, in _init_as_actual
		self._check_dimensions()
	  File "/usr/local/lib/python3.6/dist-packages/anndata/base.py", line 1878, in _check_dimensions
		.format(self._n_obs, self._obs.shape[0]))
	ValueError: Observations annot. `obs` must have number of rows of `X` (23071), but has 28789 rows.

The 23071 looks familiar, as that's the number of cells I provided in my original matrix. The 28789 I don't recognise at all. Any idea what is going on here?

**Comment by ktpolanski** [comment]
Hey, me again. I figured I'd harvest more data points for you, and test it on some other data to see what in the heck is going on. I used your simulation notebook to create a `matrix.txt` and `days.txt`, ran `wot optimal_transport` and `wot cells_by_gene_set`, and `wot trajectory` still bites the dust:

	ubuntu@mapcloud1:/mnt/endometrium/wottest$ wot trajectory --tmap tmaps --cell_set cell_sets.gmt --time 50 --out traj.txt
	/usr/local/lib/python3.6/dist-packages/numba/errors.py:104: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
	  warnings.warn(msg)
	Traceback (most recent call last):
	  File "/usr/local/bin/wot", line 11, in <module>
		sys.exit(main())
	  File "/usr/local/lib/python3.6/dist-packages/wot/__main__.py", line 23, in main
		cmd.main(command_args)
	  File "/usr/local/lib/python3.6/dist-packages/wot/commands/trajectory.py", line 23, in main
		trajectory_ds = tmap_model.compute_trajectories(populations)
	  File "/usr/local/lib/python3.6/dist-packages/wot/tmap/transport_map_model.py", line 97, in compute_trajectories
		var=pd.DataFrame(index=population_names))
	  File "/usr/local/lib/python3.6/dist-packages/anndata/base.py", line 671, in __init__
		filename=filename, filemode=filemode)
	  File "/usr/local/lib/python3.6/dist-packages/anndata/base.py", line 880, in _init_as_actual
		self._check_dimensions()
	  File "/usr/local/lib/python3.6/dist-packages/anndata/base.py", line 1878, in _check_dimensions
		.format(self._n_obs, self._obs.shape[0]))
	ValueError: Observations annot. `obs` must have number of rows of `X` (152708), but has 299472 rows.

**Comment by joshua-gould** [comment]
Thank you for reporting the error. This is fixed in version 0.4.6 of wot.

**Comment by ktpolanski** [comment]
Confirming operational. Thanks for the super quick and effective turnaround!

**Comment by geoffschieb** [comment]
Dear Krzystof,

We've recently released WOT 1.0 along with a tutorial:
https://broadinstitute.github.io/wot/tutorial/

I'm sending this message to anyone who has expressed interest recently.
Sorry for the spam.

Best,
Geoff

**Comment by leahrosen** [comment]
Hi, apologies for dragging a 3 year old issue back up, but I'm having the same issue. According to `pip list`, my wot version is `1.0.8.post2`.

```python
trajectory_ds = tmap_model.trajectories(populations)
```

gives:
```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/hps/scratch/lsf_tmpdir/hl-codon-bm-11/ipykernel_621634/2106681130.py in <module>
----> 1 trajectory_ds = tmap_model.trajectories(populations)

/nfs/research/marioni/Leah/software/conda_envs/wot/lib/python3.7/site-packages/wot/tmap/transport_map_model.py in trajectories(self, populations)
    141 
    142         return anndata.AnnData(X=np.concatenate(trajectories), obs=self.meta.copy(),
--> 143                                var=pd.DataFrame(index=population_names))
    144 
    145     def get_coupling(self, t0, t1, covariate=None):

/nfs/research/marioni/Leah/software/conda_envs/wot/lib/python3.7/site-packages/anndata/_core/anndata.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, obsp, varp, oidx, vidx)
    320                 varp=varp,
    321                 filename=filename,
--> 322                 filemode=filemode,
    323             )
    324 

/nfs/research/marioni/Leah/software/conda_envs/wot/lib/python3.7/site-packages/anndata/_core/anndata.py in _init_as_actual(self, X, obs, var, uns, obsm, varm, varp, obsp, raw, layers, dtype, shape, filename, filemode)
    524         _move_adj_mtx({"uns": self._uns, "obsp": self._obsp})
    525 
--> 526         self._check_dimensions()
    527         self._check_uniqueness()
    528 

/nfs/research/marioni/Leah/software/conda_envs/wot/lib/python3.7/site-packages/anndata/_core/anndata.py in _check_dimensions(self, key)
   1836         if "obs" in key and len(self._obs) != self._n_obs:
   1837             raise ValueError(
-> 1838                 "Observations annot. `obs` must have number of rows of `X`"
   1839                 f" ({self._n_obs}), but has {self._obs.shape[0]} rows."
   1840             )

ValueError: Observations annot. `obs` must have number of rows of `X` (22507), but has 23737 rows.
```

But when I check adata.obs it has 22507 rows, as does adata._obs, and adata._n_obs is also 22507. Do you have any idea what might be going on here?

**Comment by joshua-gould** [comment]
Is this with your own data or the tutorial data? Thanks.

**Comment by leahrosen** [comment]
It's my own. Oddly, the code was working previously with a slightly different adata object, but now it just doesn't. (previously I had all cells in an adata object, and then subset in the notebook where I ran wot; now I created a new adata object that only has the subset of cells, and it isn't working)

**Comment by joshua-gould** [comment]
Could it be possible that your cell sets refer to cells that are not in your subsetted adata object?

**Comment by leahrosen** [comment]
Thank you so much for your prompt response!

This is literally the extent of my code, so I frankly have no clue where any other cells could be coming from:
```{python}
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc

import wot

g_data = sc.read_h5ad("seurat_forTrajInf_sub.h5ad")
g_data = g_data[g_data.obs.timepoint.isin(['d3', 'd3.5', 'd4', 'd4.5', 'd5']),]
g_data.obs["day"] = [float(tp[1:]) for tp in g_data.obs.timepoint]

# create OTModel
ot_model = wot.ot.OTModel(g_data, growth_iters = 3) 
ot_model.compute_all_transport_maps(tmap_out='wot_out/sub_tmaps/')

tmap_model = wot.tmap.TransportMapModel.from_directory('wot_out/sub_tmaps/')

mature_celltypes = ["Endothelium", "Mature Somites 2", "Mature Somites 1", "Late NMP-independent Meso",
                    "NMP-derived Meso", "NMP-derived Neural", "Spinal Cord", "Late NMP-independent Neural",
                    "Separate FMH", "Mature Endoderm", "Early Endoderm", "Late Head Mesoderm"
                   ]
cell_sets = g_data.obs.loc[(g_data.obs.cluster.isin(mature_celltypes)) & (g_data.obs.timepoint == 'd5')].groupby("cluster").groups
populations = tmap_model.population_from_cell_sets(cell_sets, at_time=5.0)
trajectory_ds = tmap_model.trajectories(populations)
```

**Comment by joshua-gould** [comment]
Can you please email your data to jgould at broadinstitute dot org and I can try to debug? Thanks.
