### ISSUE TITLE
Math explanation in supplement

### ISSUE THREAD

**Issue by concatenize** [broadinstitute/wot#24]
Hi WOT developers! In your Cell paper, it looks like the mathematical supplement [here](https://www.cell.com/cms/10.1016/j.cell.2019.01.006/attachment/bc1e4ee9-6eed-49ad-94d0-5749dfb8a382/mmc8.pdf) seems to have a lot of mis-rendered LaTeX. You may want to check with the journal and see if something went wrong. Here's a screenshot.

<img width="630" alt="screen shot 2019-02-06 at 09 27 01" src="https://user-images.githubusercontent.com/39770062/52348193-bd390a80-29f1-11e9-8c4f-1dd9cd91d52d.png">

Thanks for putting this together; it looks like a titanic amount of work!

**Comment by geoffschieb** [comment]
Yes, this is an error on the Journal's side. Here is the copy that we
thought they would upload. This will be fixed online early next week.
