### ISSUE TITLE
Example: 08_plotting_validation_summary.py

### ISSUE THREAD

**Issue by putnamdk** [broadinstitute/wot#28]
Error:
File "08_plotting_validation_summary.py", line 15 in <module>
vs = wotcommands.compute_vvalidation_summary(ot_model)

TypeError: compute_validation_summary() missing 1 required positional argument: 'day_pairs_triplets'

The function in the provided example code is not using a required parameter.

**Comment by joshua-gould** [comment]
Thanks. I updated compute_validation_summary to make day_pairs_triplets optional

**Comment by putnamdk** [comment]
I downloaded the updated file, Now I have this error:

File “08_plotting_validation_summary.py”, line 15, in <module>
vs = wot.commands.compute_validation_summary(ot_model)

File optimal_transport_validation.py, line 44 in compute_validation_summary
  day_pairs_triplets.append((t0, t05, t1))
AttributeError: ‘NoneType’ object has no attribute ‘append’

Sincerely
Daniel Putnam

**Comment by joshua-gould** [comment]
Sorry, forgot to add day_pairs_triplets=[] to commit

**Comment by putnamdk** [comment]
I have made this update.  Now, I see this error:

File “08_plotting_validation_summary.py”, line 15, in <module> 
vs = wot.commands.compute_validation_summary(ot_model)

File "../wot/commands/optimal_transport_validation.py", line 55 in compute_validation_summary
ot_model.compute_all_tansport_maps(with_covariates=True)

File "../wot/ot/ot_model.py", line 213, in compute_all_transport_maps
self.compute_transport_map(*x)

File "../wot/ot/ot_model.py", line 259, in compute_transport_map
tmap = OTModel.compute_single_transport_map(self.matrix, config)

File "../wot/ot/ot_model.py", line 336, in compute_single_transport_map
tmap = wot.ot.transport_stable_learn_growth(C, **config)
TypeError: transport_stable_learn_growth() got an unexpected keyword argument 'tmap_prefix'

**Comment by putnamdk** [comment]
I didn't mean to close the comment

**Comment by YubinXie** [comment]
`TypeError: transport_stable_learn_growth() got an unexpected keyword argument 'tmap_prefix'`
Same error here.

**Comment by joshua-gould** [comment]
Thanks, I updated the python code.
