### ISSUE TITLE
Do you provide notebook that can reproduce your results in the paper?

### ISSUE THREAD

**Issue by YubinXie** [broadinstitute/wot#30]
Thanks for providing the codes. 

I was wondering if you provide Jupiter notebooks that take the real data in the paper, and produce corresponding figures. This would be helpful for us to learn how to play with our own data. I only found simulated data example in this repo and document. Thanks!

**Comment by joshua-gould** [comment]
We now have notebooks available at https://broadinstitute.github.io/wot/tutorial/.
