### ISSUE TITLE
Bugs in the codes from git page all_scripts.zip

### ISSUE THREAD

**Issue by YubinXie** [broadinstitute/wot#31]
In the first script from http://broadinstitute.github.io/wot/notebook/all_scripts.zip, the last lines are
```
wot.io.write_dataset_metadata(ds.row_meta, days_file, 'day')
wot.io.write_dataset_metadata(ds.row_meta, covariate_file, 'covariate')
```

The error will come as `ds has no attribution: row_meta`. While in other codes provided in your GitHub, the last lines are 

```
wot.io.write_dataset_metadata(ds.obs, days_file, 'day')
wot.io.write_dataset_metadata(ds.obs, covariate_file, 'covariate')
``` 
, which works fine.

**Comment by joshua-gould** [comment]
Thanks. I updated the python code.
