### ISSUE TITLE
error in local_enrichment when running for two matrices

### ISSUE THREAD

**Issue by frymor** [broadinstitute/wot#35]
Hi,

I'm running the commands using the  supplied data from the examples folder. Unfortunately I keep getting the error when running the following command.

`wot local_enrichment --score t_test --matrix1 ../wotExamples/trends_Lymphocytes.mean.txt --variance1 ../wotExamples/trends_Lymphocytes.variance.txt --matrix2 ../wotExamples/trends_Granulocytes.mean.txt --variance2 ../wotExamples/trends_Granulocytes.variance.txt`

I get this error:

```
Traceback (most recent call last):
  File "/home/USER/.local/bin/wot", line 10, in <module>
    sys.exit(main())
  File "/home/USER/.local/lib/python3.7/site-packages/wot/__main__.py", line 23, in main
    cmd.main(command_args)
  File "/home/USER/.local/lib/python3.7/site-packages/wot/commands/local_enrichment.py", line 60, in main
    ds2.variance = ds2.variance[:, ds_indices]
AttributeError: 'AnnData' object has no attribute 'variance'
```

All the other commands have worked so far.
But I'm not sure why this is happening. 

I would appreciate your help.

thanks

**Comment by joshua-gould** [comment]
Thanks, the bus is fixed now.
