### ISSUE TITLE
cells_by_gene_set creates an empty file

### ISSUE THREAD

**Issue by rojuvalu** [broadinstitute/wot#41]
I have created the necessary files. But when running the `cells_by_gene_set` command I get no cells in the file.

the command I use is 
```
wot cells_by_gene_set --matrix matrix.transposed.txt --gene_sets gene_set.gmt --out cell_sets.gmt --format gmt --quantile 0.5
```
As the files are very big, I copy-pasted here only a small subset of it. I hope it is enough.
the `matrix` looks like that:
```
id      Xkr4    Mrpl15  Lypla1  Tcea1   Rgs20   Atp6v1h ...
cell_143_AAACCTGAGGCTAGGT  -0.219520647107675      -0.729889404055677      -0.389549050946858      1.35781559781124        -0.254530089148578      2.28680657293266 ...
cell_143_AAACGGGCAATCGGTT  -0.219520647107675      -0.729889404055677      -0.389549050946858      -0.638558866199748      -0.254530089148578      -0.640469100310059  ...
cell_143_AAAGTAGCATAAAGGT  -0.219520647107675      -0.729889404055677      -0.389549050946858      -0.638558866199748      -0.254530089148578      -0.640469100310059 ...
cell_143_AAATGCCGTGTGTGCC  -0.219520647107675      -0.729889404055677      -0.389549050946858      -0.638558866199748      -0.254530089148578      -0.640469100310059  ...
...
```
the `gene_set.gmt` files is like that:

```
1       cluster Igfbpl1 Ccnd2   Tubb3   Cd24a   Sox11   Dlx6os1 Arx  ...
2       cluster Igf1    Cnr1    Crh     Snhg11  Syt1 ...
3       cluster Cspg5   Ednrb   Pdgfra  Cdo1    Emid1 ...
```
In total I have 18 different clusters containing the genes in the `gene_set.gmt` file.
But when I'm running the command it create a file with this results

```
1       -
2       -
3       -
4       -
5       -
6       -
7       -
8       -
9       -
10      -
11      -
12      -
13      -
14      -
15      -
16      -
17      -
18      -
```

any ideas what wrong here?

a few assumptions I'm making now:
- Is it possible that it is working fine, but the expression values are so low, that it can't build the cell sets? 
I tried to put the quantile also at 0, but it didn't help.
- Can I have negative values in the file?

thanks

**Comment by joshua-gould** [comment]
Sorry for the delay in our response. We've since updated the tool in github-are you able to get it working with the latest version?
