### ISSUE TITLE
optimal_transport days information missing for *** cells

### ISSUE THREAD

**Issue by ChengTao2017** [broadinstitute/wot#42]
Thanks for developing such nice analysis tool.When I run 
wot optimal_transport --matrix  my_matrix_file_path  --cell_days my_cell_day_file_path--out my_tmaps
but I got the error "Days information missing for (the cell number) cells
No day pairs"
I got the two files form as follows
https://broadinstitute.github.io/wot/cli_documentation/#matrix_file
I do no know what is the problem,I got stuck in this for few days,can you help with this?
Thanks in advance!

**Comment by frymor** [comment]
can you post here a snippet of your two files?
I mean the matrix and the day information.

I have had a similar problem. What I find out was that the day column was not identified as integer values and therefore couldn't be processed. do you have only numbers in the second column?

**Comment by ChengTao2017** [comment]
"id"	"day"
"4hpf_AAAGATGCAGCTGTAT"	4
"4hpf_AAAGCAATCAACACCA"	4
"4hpf_ACTATCTCAGCCTATA"	4
Thanks for your answer,this is my day_file snippet ,I only have numbers in the second column.
I can not figure out what is the problem.

**Comment by frymor** [comment]
is it tab-delimited?
can you also remove the "?

**Comment by ChengTao2017** [comment]
OK,I try this.

**Comment by ChengTao2017** [comment]
I have solved the problem,Thank you very much！

**Comment by frymor** [comment]
what was the problem or the solution?

**Comment by frymor** [comment]
pls close the issue, if done.

**Comment by ChengTao2017** [comment]
I remove "" in the file
