### ISSUE TITLE
cells_by_gene_set strange behavior

### ISSUE THREAD

**Issue by frymor** [broadinstitute/wot#45]
Im analysing a big data set from 10x Genomics data.
to make life easier I created a subset with "only" three time points. my gene matrix contains 10482 cells with 18418 genes. 
When running the command:
`wot cells_by_gene_set --matrix matrix --gene_sets gene_set.gmt --out cell_sets.gmt --format gmt --quantile 0.99`
I get no results, but if I sub-set the file to contain only a sample of the genes I can get a cell-set, but all (~99%, with some few exceptions) of them are grouped in one cluster).  I did this randomly with different number of cells and genes and each time a different number of cells is clustered in this one cluster, but not in other cluster.

I was wondering if there is a reason for this kind of behavior, or whether or not this is a computational problem.
I would appreciate your help. If needed I can also send the original files.

thanks

Assa

P.S.
Just an afterthought. 
To make sure that the missing results has nothing to do with the data-set structure, I would like to mention, that the gene-sets used to run the above command were created from only one of the time-points. The list of unique genes in gene-sets contains 13710 genes in 18 clusters, but only 6189 unique entries, while the list of genes in the matrix has 18417 genes. So obvious not all genes from the gene matrix are in the gene-set. 

Another thought I had - should the gene matrix used as input be in any way normalized or scaled? We are using for input data from the Seurat package. Before inputting it to wot we normalize and scale the data matrix.

**Comment by joshua-gould** [comment]
Sorry for the delay in our response. We've since updated the tool in github-are you able to get it working with the latest version?

The input matrix should be normalized and scaled.

**Comment by frymor** [comment]
Hi, thanks for the reply. I have updated to version 0.5.6. 
Unfortunately I still can't run the command. 
Now though, instead of getting an empty file and no results, I get the following error message:

```
$ wot cells_by_gene_set --matrix p2_matrix.txt --gene_sets p2_gene_set.gmt --out p2_cell_sets.gmt --format gmt --quantile 0.01

Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/envs/Waddington/bin/wot", line 10, in <module>
    sys.exit(main())
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/wot/__main__.py", line 23, in main
    cmd.main(command_args)
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/wot/commands/cells_by_gene_set.py", line 30, in main
    result = wot.get_cells_in_gene_sets(gene_sets, dataset, quantile=float(args.quantile))
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/wot/dataset_util.py", line 38, in get_cells_in_gene_sets
    dataset.obs.index[selected]
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3968, in __getitem__
    result = getitem(key)
IndexError: too many indices for array
```

The same error appears also with different quantile values. 

any ideas?
thanks Assa

**Comment by joshua-gould** [comment]
Please try installing from the master branch.

**Comment by frymor** [comment]
I don't understand. The setup.py script in the main folder contains only version 0.5.6. This is also the version I got using pip.

How do I install it from the master branch?

**Comment by joshua-gould** [comment]
```
git clone https://github.com/broadinstitute/wot.git
cd wot
pip install -e .
```

**Comment by frymor** [comment]
Done, thanks.
now I get this message:

```
wot cells_by_gene_set --matrix p2_matrix.transposed.txt --gene_sets p2_gene_set.gmt --out p2_cell_sets.gmt --format gmt --quantile 0.01
usage: cells_by_gene_set.py [-h] --score SCORE --out OUT [--quantile QUANTILE]
```

Does it means, now it works only after calculating the scores?

**Comment by joshua-gould** [comment]
Yes

**Comment by frymor** [comment]
Thanks for the great help and hope I didn't annoy to much.
Just last question about the gene- and cell-sets. As I have different timepoints for the developmental series, I create gene-sets for all three time points, but as you can imagine, they differ a bit. Is it possible to use the three sets in one go? does it make sense to combine them together into one bigger file with more clusters, or should they even be analyzed completely separated?

**Comment by joshua-gould** [comment]
When you specify a cell set (e.g. in the trajectory tool), you also need to specify the timepoint. The tool then filters all cells in your cell set to only include cells on your specified day. Does that make sense?

**Comment by frymor** [comment]
Yes, this makes sense. But the question is for one step previously. Would it make more sense to create the cell-sets based on the gene-sets from one specific time-point, Should we combine all the gene-sets into one big file or is there a way to use all the different time-points separately in the calculations?

**Comment by geoffschieb** [comment]
Typically there is not necessarily a different gene set for each time
point. Suppose you make a gene signature for "Fibroblast Identity". This
concept does not change over time. Then you score all cells over all time
points according to the signature and pick a cut off to define the cell
set. This is the "Fibroblast Cell Set". Then you can slice this global cell
set to get a cell set at different time points (e.g. "Fibroblasts at Day
3"). You can then compute the descendants of "Fibroblasts at Day 3" on Day
4.

What you're trying to do with having a different gene set for each time
point sounds overly complicated. If you must do it for some reason, you can
write a for loop.

Best,
Geoff

**Comment by frymor** [comment]
Thanks. I think I get it now.
