### ISSUE TITLE
reading tmap files

### ISSUE THREAD

**Issue by zinagood** [broadinstitute/wot#46]
Hello Joshua,

I'm a postdoc working on engineered T cells at Stanford university and hope to use WOT.

I've generated maps from the attached data matrix and days file using the following command:
wot optimal_transport --matrix matrix.txt --cell_days days.txt --local_pca 0 --out tmaps

However, I can't seem to solve the error in calculating the trajectory generated by this command (screenshot attached):
wot trajectory --tmap tmaps --cell_set naive.gmt --day 10 --out wot_trajectory.txt

I'm also attaching the gmt file used for this command that contains the following information.
Tip1 naive CD8_HA_D0_213 CD8_HA_D0_298 CD8_HA_D0_362 CD8_HA_D0_413 CD8_HA_D0_561 CD8_HA_D0_722 CD8_HA_D0_798 CD8_HA_D0_829 CD8_HA_D0_893 CD8_HA_D0_896

The issue appears to be with getting information out of the loom files. Could ou please help?

Thanks in advance,
Zina

![wot-error](https://user-images.githubusercontent.com/8445659/55659364-31a3e600-57b6-11e9-952d-6778adedd738.png)
[matrix.txt](https://github.com/broadinstitute/wot/files/3049827/matrix.txt)
[days.txt](https://github.com/broadinstitute/wot/files/3049828/days.txt)
[naive.txt](https://github.com/broadinstitute/wot/files/3049830/naive.txt)

**Comment by joshua-gould** [comment]
Transport map files were corrupted. Fixed by regenerating.

**Comment by geoffschieb** [comment]
Hi Zinaida,

We have just released WOT 1.0, along with a tutorial:
https://broadinstitute.github.io/wot/tutorial/

I'm sending this to anyone who has expressed interest recently.

Best,
Geoff

Be

**Comment by zinagood** [comment]
Nice! Thanks so much!!
Zina
