### ISSUE TITLE
neighborhood_graph produces .gexf file instead of .csv and .h5ad files

### ISSUE THREAD

**Issue by mthjwu** [broadinstitute/wot#47]
Hi WOT team,

wot neighborhood_graph is supposed to produce .csv and .h5ad files that is used for following steps, but now it produces .gexf file instead, and there is no document about how to use it. 
Thanks!

**Comment by joshua-gould** [comment]
Thanks. I updated the documentation (https://broadinstitute.github.io/wot/cli_documentation/#embedding). The tool produces a gexf file which you can use as input to Gephi or https://github.com/klarman-cell-observatory/forceatlas2

**Comment by mthjwu** [comment]
Thanks for your response. But <wot trajectory> command "--embedding" needs a .csv file to perform, right? How to get the .csv file from .gexf file?

**Comment by joshua-gould** [comment]
You need to compute a 2d embedding (e.g. using Gephi or
https://github.com/klarman-cell-observatory/forceatlas2)

**Comment by geoffschieb** [comment]
Hi mthjwu,

We have just released WOT 1.0 along with a tutorial:
https://broadinstitute.github.io/wot/tutorial/

Best,
Geoff
