### ISSUE TITLE
cell-sets from gene scores

### ISSUE THREAD

**Issue by frymor** [broadinstitute/wot#48]
Hi, I have a question to your example script in `docs/examples/code/run_example.sh`.

In there there is a way to calculate the cell-sets using gene scores. This is done by first computing the gene scores via the script `wot gene_set_scores ...`. This create several two-column lists for each of the clusters which can than be used in the script 
`wot cells_by_gene_set --score LIST_of_SCORES ...`

But unfortunately this is not working anymore, as the script complains about missing files:
```
wot cells_by_gene_set --score gene_set_scores.txt_Cluster10.txt --score gene_set_scores.txt_Cluster11.txt ... --score gene_set_scores.txt_Cluster9.txt --out cell_sets_scores.gmt
usage: cells_by_gene_set.py [-h] --matrix MATRIX --gene_sets GENE_SETS
                            [--out OUT] [--format {gmt,gmx,txt}]
                            [--quantile QUANTILE]
cells_by_gene_set.py: error: the following arguments are required: --matrix, --gene_sets
```

Is there a way to test this way of calculating cell-sets? Why was this function defunct?

**Comment by frymor** [comment]
Hi, I have a question to your example script in `docs/examples/code/run_example.sh`.

In there there is a way to calculate the cell-sets using gene scores. This is done by first computing the gene scores via the script `wot gene_set_scores ...`. This create several two-column lists for each of the clusters which can than be used in the script 
`wot cells_by_gene_set --score LIST_of_SCORES ...`

But unfortunately this is not working anymore, as the script complains about missing files:
```
wot cells_by_gene_set --score gene_set_scores.txt_Cluster10.txt --score gene_set_scores.txt_Cluster11.txt ... --score gene_set_scores.txt_Cluster9.txt --out cell_sets_scores.gmt
usage: cells_by_gene_set.py [-h] --matrix MATRIX --gene_sets GENE_SETS
                            [--out OUT] [--format {gmt,gmx,txt}]
                            [--quantile QUANTILE]
cells_by_gene_set.py: error: the following arguments are required: --matrix, --gene_sets
```

Is there a way to test this way of calculating cell-sets? Why was this function defunct?

**Comment by joshua-gould** [comment]
Please install from the master branch. We will push an update to pip soon.

**Comment by frymor** [comment]
I don't understand. The setup.py script in the main folder contains only version 0.5.6. This is also the version I got using pip.

How do I install it from the master branch?

**Comment by joshua-gould** [comment]
```
git clone https://github.com/broadinstitute/wot.git
cd wot
pip install -e .
```

**Comment by frymor** [comment]
this works. thanks a lot.
