### ISSUE TITLE
TypeError in Computing Transport Maps (WOT v1.0)

### ISSUE THREAD

**Issue by missacruzz** [broadinstitute/wot#52]
Hi,

I'm trying to re-calculate transport maps via the command line using WOT v1.0 (installed via pip 5/13/19), but it returns a type error. From what I can see, the argument is specified in optimal_transport.py but not in /ot/ot_model.py. 

>File "/miniconda2/envs/waddingtonOT/bin/wot", line 10, in <module>
    sys.exit(main())
  File "/miniconda2/envs/waddingtonot/lib/python3.7/site-packages/wot/__main__.py", line 21, in main
    cmd.main(command_args)
  File "/miniconda2/envs/waddingtonot/lib/python3.7/site-packages/wot/commands/optimal_transport.py", line 27, in main
    tmap_out=args.out)
TypeError: compute_all_transport_maps() got an unexpected keyword argument 'no_overwrite'

**Comment by joshua-gould** [comment]
Fixed in version 1.0.1. Thanks.
