### ISSUE TITLE
Gene Set Scores Error: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by missacruzz** [broadinstitute/wot#54]
Hi,

After resolution of the previous TypeError with scoring gene sets, I encountered the following error with both test files and my own data both using API and the command line interface (this is after updating the gene_set_scores file pushed to master earlier). From what I can see, my guess would be a bug in the read_sets function. 

/miniconda2/envs/waddingtonot/lib/python3.7/site-packages/wot/gene_set_scores.py:101: RuntimeWarning: invalid value encountered in true_divide
  x = (x - mean) / std

**Comment by joshua-gould** [comment]
I'm unable to reproduce this error with the tutorial data. You will
encounter this message if a gene in a gene set has a standard deviation of
zero.

**Comment by missacruzz** [comment]
I encounter this data using the _test_ dataset (in the test folder), not the tutorial dataset. I also encounter this with my own gene set & dataset. Thanks.

**Comment by missacruzz** [comment]
Hi, I was wondering if you were able to reproduce the error with the test files under the test folder? I still have this issue after upgrading via pip
