### ISSUE TITLE
Installation error on MacOSX

### ISSUE THREAD

**Issue by ghoshal** [broadinstitute/wot#59]
Hi,

I am trying to install WOT using pip on my Mac OSX but I am getting this error. I have xcode and command line tools installed already.

Collecting wot
  Using cached https://files.pythonhosted.org/packages/93/b0/6ff94e54ca48a2764343f04ae03bc958c8de4b97eb151427324aa96ab7b7/wot-1.0.2-py2.py3-none-any.whl
Collecting POT (from wot)
  Using cached https://files.pythonhosted.org/packages/28/4b/7aaa1f840a359f5953dd378e0237fa8faf9b0a415ff7282b7375fbe68d27/POT-0.5.1.tar.gz
Requirement already satisfied: pandas in ./anaconda3/lib/python3.7/site-packages (from wot) (0.23.4)
Requirement already satisfied: scikit-learn in ./anaconda3/lib/python3.7/site-packages (from wot) (0.20.3)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.7/site-packages (from wot) (3.0.2)
Requirement already satisfied: scanpy>=1.4.2 in ./anaconda3/lib/python3.7/site-packages (from wot) (1.4.3)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.7/site-packages (from wot) (1.1.0)
Requirement already satisfied: h5py in ./anaconda3/lib/python3.7/site-packages (from wot) (2.9.0)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from wot) (1.15.4)
Requirement already satisfied: cython in ./anaconda3/lib/python3.7/site-packages (from POT->wot) (0.29.2)
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.7/site-packages (from pandas->wot) (2.7.5)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.7/site-packages (from pandas->wot) (2018.7)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->wot) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->wot) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->wot) (2.3.0)
Requirement already satisfied: statsmodels in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (0.9.0)
Requirement already satisfied: numba>=0.41.0 in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (0.43.1)
Requirement already satisfied: tables in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (3.5.1)
Requirement already satisfied: joblib in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (0.13.2)
Requirement already satisfied: anndata>=0.6.15 in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (0.6.19)
Requirement already satisfied: networkx in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (2.2)
Requirement already satisfied: patsy in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (0.5.1)
Requirement already satisfied: natsort in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (6.0.0)
Requirement already satisfied: seaborn in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (0.9.0)
Requirement already satisfied: tqdm in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (4.28.1)
Requirement already satisfied: umap-learn>=0.3.0 in ./anaconda3/lib/python3.7/site-packages (from scanpy>=1.4.2->wot) (0.3.8)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from h5py->wot) (1.12.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->wot) (41.0.0)
Requirement already satisfied: llvmlite>=0.28.0dev0 in ./anaconda3/lib/python3.7/site-packages (from numba>=0.41.0->scanpy>=1.4.2->wot) (0.28.0)
Requirement already satisfied: numexpr>=2.6.2 in ./anaconda3/lib/python3.7/site-packages (from tables->scanpy>=1.4.2->wot) (2.6.8)
Requirement already satisfied: mock>=2.0 in ./anaconda3/lib/python3.7/site-packages (from tables->scanpy>=1.4.2->wot) (2.0.0)
Requirement already satisfied: decorator>=4.3.0 in ./anaconda3/lib/python3.7/site-packages (from networkx->scanpy>=1.4.2->wot) (4.3.0)
Requirement already satisfied: pbr>=0.11 in ./anaconda3/lib/python3.7/site-packages (from mock>=2.0->tables->scanpy>=1.4.2->wot) (5.1.3)
Building wheels for collected packages: POT
  Building wheel for POT (setup.py) ... error
  ERROR: Complete output from command /Users/bibaswan/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-install-6zgo6l_s/POT/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-wheel-cpzq215_ --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/bregman.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/plot.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/stochastic.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/datasets.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/dr.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/utils.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/smooth.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/gromov.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/optim.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  copying ot/da.py -> build/lib.macosx-10.7-x86_64-3.7/ot
  creating build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  copying ot/gpu/bregman.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  copying ot/gpu/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  copying ot/gpu/utils.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  copying ot/gpu/da.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
  creating build/lib.macosx-10.7-x86_64-3.7/ot/lp
  copying ot/lp/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/lp
  copying ot/lp/cvx.py -> build/lib.macosx-10.7-x86_64-3.7/ot/lp
  creating build/lib.macosx-10.7-x86_64-3.7/ot/externals
  copying ot/externals/funcsigs.py -> build/lib.macosx-10.7-x86_64-3.7/ot/externals
  copying ot/externals/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/externals
  running build_ext
  building 'ot.lp.emd_wrap' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/ot
  creating build/temp.macosx-10.7-x86_64-3.7/ot/lp
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/bibaswan/anaconda3/include -arch x86_64 -I/Users/bibaswan/anaconda3/include -arch x86_64 -Iot/lp -I/Users/bibaswan/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-install-6zgo6l_s/POT/ot/lp -I/Users/bibaswan/anaconda3/include/python3.7m -c ot/lp/emd_wrap.cpp -o build/temp.macosx-10.7-x86_64-3.7/ot/lp/emd_wrap.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /Users/bibaswan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                   from /Users/bibaswan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                   from /Users/bibaswan/anaconda3/include/python3.7m/Python.h:11,
                   from ot/lp/emd_wrap.cpp:28:
  /Users/bibaswan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for POT
  Running setup.py clean for POT
Failed to build POT
Installing collected packages: POT, wot
  Running setup.py install for POT ... error
    ERROR: Complete output from command /Users/bibaswan/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-install-6zgo6l_s/POT/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-record-9h8k9k_e/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/bregman.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/plot.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/stochastic.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/datasets.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/dr.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/utils.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/smooth.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/gromov.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/optim.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    copying ot/da.py -> build/lib.macosx-10.7-x86_64-3.7/ot
    creating build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    copying ot/gpu/bregman.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    copying ot/gpu/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    copying ot/gpu/utils.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    copying ot/gpu/da.py -> build/lib.macosx-10.7-x86_64-3.7/ot/gpu
    creating build/lib.macosx-10.7-x86_64-3.7/ot/lp
    copying ot/lp/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/lp
    copying ot/lp/cvx.py -> build/lib.macosx-10.7-x86_64-3.7/ot/lp
    creating build/lib.macosx-10.7-x86_64-3.7/ot/externals
    copying ot/externals/funcsigs.py -> build/lib.macosx-10.7-x86_64-3.7/ot/externals
    copying ot/externals/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ot/externals
    running build_ext
    building 'ot.lp.emd_wrap' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/ot
    creating build/temp.macosx-10.7-x86_64-3.7/ot/lp
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/bibaswan/anaconda3/include -arch x86_64 -I/Users/bibaswan/anaconda3/include -arch x86_64 -Iot/lp -I/Users/bibaswan/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-install-6zgo6l_s/POT/ot/lp -I/Users/bibaswan/anaconda3/include/python3.7m -c ot/lp/emd_wrap.cpp -o build/temp.macosx-10.7-x86_64-3.7/ot/lp/emd_wrap.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /Users/bibaswan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                     from /Users/bibaswan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                     from /Users/bibaswan/anaconda3/include/python3.7m/Python.h:11,
                     from ot/lp/emd_wrap.cpp:28:
    /Users/bibaswan/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/bibaswan/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-install-6zgo6l_s/POT/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-record-9h8k9k_e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/lv/26lkh7m902n85b7k_m_0gz_80000gn/T/pip-install-6zgo6l_s/POT/

Any help would be awesome.

**Comment by ghoshal** [comment]
Hi,

The problem was happening in the command line tools.  Needed to go to /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg location and install package manually. That solved the problem.

P.S. I had cython installed already.

Thanks

**Comment by samIndeed** [comment]
Hi,

I'm getting the same error and I have cython installed and manually installing those headers didn't work

**Comment by joshua-gould** [comment]
Please try installing POT with conda: conda install -c conda-forge pot

**Comment by samIndeed** [comment]
Oh actually I fixed it already with 

conda install -c anaconda gcc 

Thanks!
