### ISSUE TITLE
calculting trajectories gives a warning "Variable names are not unique"

### ISSUE THREAD

**Issue by frymor** [broadinstitute/wot#62]
when running the command 
```
 wot trajectory --tmap tmaps1.0.2 --cell_set Output1.0.2/cell_sets_scores.gmt --day 10 --out traj_
```
I get the following warning (?)
```
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
```

Can it be ignored? How can I avoid it or modify the inout file, so that it would not show again?
where does it look for/find duplicated entries?
By manually looking at the file I couldn't find any duplicated gene entries

thanks

**Comment by joshua-gould** [comment]
This is a warning-you can ignore
