### ISSUE TITLE
tmap_model.trajectories fails with two time points

### ISSUE THREAD

**Issue by concatenize** [broadinstitute/wot#63]
I'm excited to try out WOT on some public data! But, I ran into an obstacle when testing modifications of notebook 4 on a small subset of the data.

`tmap_model.trajectories` seems to only work when 3 or more time-points are present. You can verify this in notebook 4 by deleting all but the 17.5-18.0 map. The error with only these two time-points is `ValueError: No cells found at the given day`, which is confusing because there are plenty of 18.0 cells in the relevant `Population` object. It would be nice to have an informative error message when only two time points are present. 

This may be related to https://github.com/broadinstitute/wot/issues/25 .

**Comment by joshua-gould** [comment]
Fixed bug when reading transport maps with only two time points
