### ISSUE TITLE
Read dataset from 10x h5 file

### ISSUE THREAD

**Issue by huangxingnan1994** [broadinstitute/wot#67]
Hi wot team,
I have some problems about how to use your module. When I tried to import data from an h5 file generated by cellranger3, it always gave me the ValueError. 
<img width="1174" alt="valueerror" src="https://user-images.githubusercontent.com/53215509/61699598-c6365200-ad6d-11e9-9f9e-b691ea40e816.png">
could you tell me how to specify the genome, please?

**Comment by joshua-gould** [comment]
IO is updated in version 1.0.6.
