### ISSUE TITLE
Modify read_anndata to read cellranger v3 matrices

### ISSUE THREAD

**Issue by gabprg** [broadinstitute/wot#68]
Hi there,

I was looking into the code to read in data (read_anndata function) - in the case of reading from a matrix file, as it would be if reading the output of the cellranger pipeline, the gene-level annotation file is now called features.tsv.gz, instead of genes.tsv.gz . It would be great to modify the function to look for that as well, instead of throwing an error (it's an easy fix either way, but wanted to point it out!).

Thanks for developing a great trajectory analysis tool!

Gabi

**Comment by joshua-gould** [comment]
Thanks for pointing this out. We will fix shortly.

**Comment by joshua-gould** [comment]
IO is updated in version 1.0.6.
