### ISSUE TITLE
'AnnData' object has no attribute 'to_anndata'

### ISSUE THREAD

**Issue by hahia** [broadinstitute/wot#82]
Hello,
I install the anndata use pip install anndata, the version is 0.7.4, but when I run, there happen a bug
**'AnnData' object has no attribute 'to_anndata'**
![image](https://user-images.githubusercontent.com/49113803/90975330-c7841080-e565-11ea-93b1-1763212ed401.png)

Anyone known how to solve this? Thanks any comments!!!

**Comment by joshua-gould** [comment]
Version wot-1.0.8.post2 fixes this issue.
