### ISSUE TITLE
where to choose number of PCA  to compute transport map?

### ISSUE THREAD

**Issue by hahia** [broadinstitute/wot#84]
Hello, 
Recently, I use the command 
```
ot_model = wot.ot.OTModel(adata, epsilon = 0.05, lambda1 = 1, lambda2 = 5, growth_iters = 5)
ot_model.compute_all_transport_maps(tmap_out='tmaps/neuron_1_5_5/neuron')
```
How much dimensional local PCA space use to compute transport map? I don't see some parameters about this.

**Comment by joshua-gould** [comment]
You can pass local_pca to the OTModel constructor.

**Comment by hahia** [comment]
> You can pass local_pca to the OTModel constructor.

If I don't pass local_pca to OTModel, it will compute local pca between adjacent timepoint? and what the default number of PCA? 
Is there have docs about the function and parameters?
Thank you for your replay.

**Comment by joshua-gould** [comment]
Please see the line 85 for the source for OTModel for defaults-https://github.com/broadinstitute/wot/blob/master/wot/ot/ot_model.py#L85
